#cloud-config

coreos:
    units:
    -
        name: update-sysctl.service
        command: start
        content: |
          [Unit]
          Description=Update sysctl values written by cloud-config
          [Service]
          ExecStart=/usr/lib/systemd/systemd-sysctl
    -
        name: iptables-restore.service
        command: start
    -
        name: docker.service
        drop-ins:
            - name: 10-log-level.conf
              content: |
                  [Service]
                  Environment="DOCKER_OPTS=--log-level=warn"
    -
        name: amazon-ecs-agent.service
        command: start
        runtime: true
        content: |
            [Unit]
            Description=AWS ECS Agent
            Documentation=https://docs.aws.amazon.com/AmazonECS/latest/developerguide/
            Requires=docker.socket logspout.service
            After=docker.socket logspout.service

            [Service]
            Environment=ECS_CLUSTER=${ecs-cluster-name}
            Environment=ECS_LOGLEVEL=warn
            Environment=ECS_AGENT_TAG=${ecs-agent-docker-tag}
            Restart=on-failure
            RestartSec=30
            RestartPreventExitStatus=5
            SyslogIdentifier=ecs-agent
            ExecStartPre=-/bin/mkdir -p /var/log/ecs /var/ecs-data /etc/ecs
            ExecStartPre=-/usr/bin/touch /etc/ecs/ecs.config
            ExecStartPre=-/usr/bin/docker kill ecs-agent
            ExecStartPre=-/usr/bin/docker rm ecs-agent
            ExecStartPre=/usr/bin/docker pull amazon/amazon-ecs-agent:$${ECS_AGENT_TAG}
            ExecStart=/usr/bin/docker run --name ecs-agent --hostname ecs-agent\
                                         --env-file=/etc/ecs/ecs.config \
                                         --net=host \
                                         --volume=/var/run/docker.sock:/var/run/docker.sock \
                                         --volume=/var/log/ecs:/log \
                                         --volume=/var/ecs-data:/data \
                                         --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                                         --volume=/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
                                         --publish=127.0.0.1:51678:51678 \
                                         --env=ECS_LOGFILE=/log/ecs-agent.log \
                                         --env=ECS_LOGLEVEL=$${ECS_LOGLEVEL} \
                                         --env=ECS_DATADIR=/data \
                                         --env=ECS_CLUSTER=$${ECS_CLUSTER} \
                                         amazon/amazon-ecs-agent:$${ECS_AGENT_TAG}
    -
        name: papertrail.service
        command: start
        runtime: true
        content: |
            [Unit]
            Description=Papertrail Forwarder Service
            Documentation=http://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-systemd/
            Requires=systemd-journald.service
            After=systemd-journald.service network.target

            [Service]
            ExecStart=/bin/sh -c "journalctl -f | ncat --ssl --ssl-verify ${syslog-host} ${syslog-port}"
            TimeoutStartSec=0
            Restart=on-failure
            RestartSec=5s

            [Install]
            WantedBy=multi-user.target
    -
        name: logspout.service
        command: start
        runtime: true
        content: |
            [Unit]
            Description=Logspout Forwarder Service
            Requires=docker.socket
            After=docker.socket

            [Service]
            TimeoutStartSec=0
            Restart=always
            RestartSec=30s
            Environment=LOGSPOUT_TAG=${logspout-docker-tag}
            Environment=LOGSPOUT_SYSLOG_TAG={{.Container.Config.Hostname}}
            ExecStartPre=-/usr/bin/docker kill logspout
            ExecStartPre=-/usr/bin/docker rm logspout
            ExecStartPre=/usr/bin/docker pull gliderlabs/logspout:$${LOGSPOUT_TAG}
            ExecStart=/usr/bin/docker run --name logspout --hostname logspout \
                                    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
                                    --env SYSLOG_HOSTNAME=%H \
                                    --env SYSLOG_TAG=$${LOGSPOUT_SYSLOG_TAG} \
                                    --env INACTIVITY_TIMEOUT=1m \
                                    gliderlabs/logspout:$${LOGSPOUT_TAG} \
                                    syslog+tls://${syslog-host}:${syslog-port}
            ExecStop=/usr/bin/docker stop logspout

            [Install]
            WantedBy=multi-user.target
    -
        name: docker-gc.service
        runtime: true
        content: |
            [Unit]
            Description=Docker Garbage Collection
            Requires=docker.socket
            After=docker.socket
            Documentation=https://github.com/spotify/docker-gc

            [Service]
            Type=oneshot
            ExecStartPre=/usr/bin/docker pull spotify/docker-gc
            ExecStart=/usr/bin/docker run --hostname docker-gc\
                                    --volume /var/run/docker.sock:/var/run/docker.sock \
                                    --volume /etc:/etc \
                                    --env GRACE_PERIOD_SECONDS=7200 \
                                    spotify/docker-gc
    -
        name: docker-gc.timer
        command: start
        content: |
            [Unit]
            Description=Run Docker Garbage Collector periodically

            [Timer]
            OnCalendar=0/1:00:00
            Persistent=true

            [Install]
            WantedBy=timers.target
    -
        name: manage-users.service
        runtime: true
        content: |
            [Unit]
            Description=Manage Users

            [Service]
            ExecStart=/opt/bin/manage-users ${ssh-iam-group}
    -
        name: manage-users.timer
        command: start
        content: |
            [Unit]
            Description=Run Manage Users every 15 minutes

            [Timer]
            OnBootSec=1min
            OnUnitInactiveSec=15min
            Persistent=true

            [Install]
            WantedBy=timers.target
write_files:
    -
        path: "/opt/bin/manage-users"
        permissions: "0755"
        owner: "root"
        encoding: "base64"
        content: |
            ${manage-users-script}
    -
        path: "/etc/ssh/sshd_config"
        permissions: "0777"
        owner: "root:root"
        encoding: "base64"
        content: |
          ${sshd-config}
    -
        path: "/etc/ecs/ecs.config"
        permissions: "0644"
        owner: "root:root"
        encoding: "base64"
        content: |
          ${ecs-config}
    -
        path: "/etc/sysctl.d/route.conf"
        permissions: "0644"
        owner: "root:root"
        content: |
          net.ipv4.conf.all.route_localnet=1
    -
        path: "/var/lib/iptables/rules-save"
        permissions: "0644"
        owner: "root:root"
        content: |
          *nat
          -A PREROUTING -p tcp -d 169.254.170.2 --dport 80 -j DNAT --to-destination 127.0.0.1:51679
          -A OUTPUT -d 169.254.170.2 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 51679
          COMMIT
